--- #YAML:1.0
name:               Hash-Case
version:            1.02
abstract:           Play trics with hash keys
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Report:  0.26
    Test::More:   0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
